services:
  # PostgreSQL for Inventory Service
  postgres-inventory:
    image: postgres:15
    container_name: routewise-postgres-inventory
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432" # Expose to a different host port to avoid conflict
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - routewise-network

#  # PostgreSQL for Order Service
#  postgres-order:
#    image: postgres:15
#    container_name: routewise-postgres-order
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: order_db
#    ports:
#      - "5434:5432"
#    volumes:
#      - order-db-data:/var/lib/postgresql/data
#    networks:
#      - routewise-network

  # RabbitMQ Message Broker with UI
  rabbitmq:
    image: rabbitmq:3-management
    container_name: routewise-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP protocol (internal)
      - "15672:15672" # RabbitMQ UI (http://localhost:15672)
    networks:
      - routewise-network

  # Inventory Service
  inventory-service:
    build: ./inventory-service
    container_name: routewise-inventory
    ports:
      - "8081:8081"
    depends_on:
      - postgres-inventory
      - rabbitmq
    networks:
      - routewise-network

  # Order Service (Placeholder for now)
#  order-service:
#    build: ./order-service
#    container_name: routewise-order
#    ports:
#      - "8082:8082"
#    depends_on:
#      - postgres-order
#      - rabbitmq
#    networks:
#      - routewise-network

volumes:
  inventory-db-data:
#  order-db-data:

networks:
  routewise-network:
