services:
  postgres:
    image: postgres:15
    container_name: routewise-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: routewise_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - routewise-network

  # RabbitMQ Message Broker with Management UI
  rabbitmq:
    image: rabbitmq:3-management
    container_name: routewise-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP protocol port (used by services to connect)
      - "15672:15672" # Management UI (open http://localhost:15672)
    networks:
      - routewise-network

#  # (Optional for later) Prometheus - Monitoring Tool
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: routewise-prometheus
#    restart: unless-stopped
#    ports:
#      - "9090:9090"  # Prometheus UI (http://localhost:9090)
#    volumes:
#      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Config file
#    networks:
#      - routewise-network
#
#  # (Optional for later) Grafana - Dashboard Visualization
#  grafana:
#    image: grafana/grafana:latest
#    container_name: routewise-grafana
#    restart: unless-stopped
#    ports:
#      - "3000:3000"  # Grafana UI (http://localhost:3000)
#    networks:
#      - routewise-network
#    volumes:
#      - grafana-data:/var/lib/grafana  # Persist Grafana dashboards

volumes:
  postgres-data:
#  grafana-data:

networks:
  routewise-network:   # Custom network so services can discover each other
